CREATE DATABASE IF NOT EXISTS HOTEL_MANAGEMENT_SYSTEM;

USE HOTEL_MANAGEMENT_SYSTEM;

CREATE TABLE IF NOT EXISTS Guests (
    GuestID INT PRIMARY KEY,
    Name varchar(50) NOT NULL,
    Contact varchar(12) NOT NULL UNIQUE,
    Email varchar(70) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Rooms (
	
    RoomID INT PRIMARY KEY,
    RoomType varchar(20) NOT NULL,
    Price decimal(10,2) NOT NULL,
    AvaibilityStatus boolean NOT NULL DEFAULT FALSE
    
);

CREATE TABLE IF NOT EXISTS Bookings (
	
    BookingID INT PRIMARY KEY,
    GuestID INT ,
    RoomID INT ,
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL,
    
    FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (GuestID) REFERENCES Guests(GuestID) 
    ON DELETE CASCADE
    ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS Payments (
    PaymentID INT PRIMARY KEY,
    BookingID INT,
    Amount DECIMAL(10 , 2 ) NOT NULL,
    PaymentDate DATE NOT NULL,
    FOREIGN KEY (BookingID)
        REFERENCES Bookings (BookingID)
        ON DELETE CASCADE ON UPDATE CASCADE
);